### PR TITLE
Lay out a periodic table

### PR DESCRIPTION
**Pull request by bsmith**
It's at a stage where it puts the elements in the right position!
Only slightly inspired by the RSC's table (https://www.rsc.org/periodic-table/)

I'm marking this just as a draft because I don't want to merge it until after:

- [x] Cordu sets up pages for each element
- [x] then I can link to them
- [x] display the proper information in each box
- [x] add CSS classes so we can choose different colours for elements, or whatever we'd like.

Screenshot 2022-12-17 at 13 01 30

### CODE REVIEW

**Comment by bsmith** [comment]
That's all I'm going to do on this for now.  The colours are just a placeholder.

There's CSS classes for things like different groups of elements or liquid/gas/solid so we can do _any_ styling we want.  The component should also be able to do things like only display some elements rather than all of them, if you pass a filtered list of data to it (not tested!).

Screenshot 2022-12-17 at 14 42 36

**Comment by JennaMclelland** [comment]
This is really cool @bsmith , really awesome notes explaining each addition too. 
Do you want to merge it to main?

**Review by JennaMclelland — APPROVED** [review]
This is epic

**Review by rich-back — APPROVED** [review]
Absolutely love it!! Top work Ben!

**Pull request merged**
